# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'CRANA'
tagline:          'Cain Road Area Neighborhood Association'
description:      Cain Road Area Neighborhood Association
url:              https://www.crana.net
baseurl:          /

author:
  name:           'Richee'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
#  repo:           https://github.com/poole/hyde
 

gems: [jekyll-paginate]
